#服务信息
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://119.3.253.37/study?charactorEncoding=utf-8&useSSL=false
    username: admin
    password: Left@sun23.
  jpa:
    show-sql: true
  application:
    name: product
server:
  port: 9011
#eruka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
#ribbon客户端负载
ribbon:
  eureka:
    enabled: true