spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://119.3.253.37/study?charactorEncoding=utf-8&useSSL=false
    username: admin
    password: Left@sun23.
  jpa:
    show-sql: true
server:
  port: 9011